apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-applicationset-controller.yml
  - argocd-cm.yml
  - argocd-dex-server.yml
  - argocd-metrics.yml
  - argocd-no-tls.yml
  - argocd-nodeport.yml
  - argocd-notifications-cm.yml
  - argocd-notifications-controller-metrics.yml
  - argocd-rbac-cm.yml
  - argocd-repo-server.yml
  - argocd-server-metrics.yml
  - customer-apps-appset.yml
